version: "3.9"

services:
  app:
    image: my-python-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: newdb
    restart: unless-stopped

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newdb   # auto-create `newdb` to match app config
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - mysql_data:/var/lib/mysql  # Persist database data
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
